blank_issues_enabled: false
contact_links:
  - name: "⛔ Support or Question"
    url: https://discord.gg/ffTDcauqyZ
    about: "For faster answers to questions, it's best to ask in the Discord chat instead of here. You'll get help much quicker!"
