name: Sync Release to Gitee

on:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release on Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          echo "Creating release $RELEASE_TAG on Gitee..."

          # 使用 jq 构建 JSON，安全处理多行 body
          payload=$(jq -n \
            --arg tag "$RELEASE_TAG" \
            --arg name "$RELEASE_NAME" \
            --arg body "$RELEASE_BODY" \
            --arg commit "master" \
            '{
              access_token: env.GITEE_TOKEN,
              tag_name: $tag,
              name: $name,
              body: $body,
              target_commitish: $commit
            }'
          )

          echo "Payload:"
          echo "$payload"

          curl -s -X POST "https://gitee.com/api/v5/repos/blikvm/blikvm/releases" \
            -H "Content-Type: application/json" \
            -d "$payload" | tee gitee_release.json

      - name: Upload release assets to Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "Uploading assets to Gitee..."

          # 获取 GitHub release 附件 URL
          assets_url="${{ github.event.release.assets_url }}"
          echo "Fetching assets from $assets_url"

          # 获取附件列表
          curl -s -H "Authorization: token ${{ github.token }}" $assets_url | jq -r '.[].browser_download_url' > urls.txt

          while read url; do
            if [ -z "$url" ]; then
              continue
            fi
            file=$(basename "$url")
            echo "Downloading $file from GitHub..."
            curl -L -o "$file" "$url"

            echo "Uploading $file to Gitee..."
            curl -s -X POST "https://gitee.com/api/v5/repos/blikvm/blikvm/releases/assets?access_token=${GITEE_TOKEN}" \
              -F "file=@${file}" \
              -F "tag_name=${RELEASE_TAG}"
          done < urls.txt
