name: Resign Tags on Release

on:
  push:
    tags:
      - '*'

jobs:
  resign_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up GPG
      uses: trustin/gpg-action@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
    
    - name: Resign tags and push
      run: |
        # Ensure GPG is set up for signing
        export GPG_TTY=$(tty)
    
        # Get all tags
        TAGS=$(git tag)
    
        for TAG in $TAGS; do
          echo "Resigning tag: $TAG"
          
          # Save the tag message (if any)
          MESSAGE=$(git for-each-ref --format='%(contents)' refs/tags/$TAG)
          
          # Delete old tag locally
          git tag -d "$TAG"
          
          # Recreate signed tag with the same message
          git tag -s "$TAG" -m "$MESSAGE"
        done
    
        # Force-push all tags
        git push --force --tags
    
    - name: Success
      run: echo "All tags successfully resigned and pushed!"
